all

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -28,9 +28,6 @@ jobs:
         with:
           terraform_version: 1.5.0
 
-      - name: Change to infra directory
-        run: cd infra
-
       - name: Run Terraform and capture outputs
         working-directory: infra
         env:
@@ -41,27 +38,32 @@ jobs:
           terraform apply -auto-approve
           terraform output -json > "$GITHUB_WORKSPACE/outputs.json"
 
-
       - name: Verify JSON Output Exists
         run: |
-          if [ ! -f outputs.json ]; then
+          if [ ! -f "$GITHUB_WORKSPACE/outputs.json" ]; then
             echo "Error: outputs.json was not created"
             exit 1
           else
-            cat outputs.json
+            cat "$GITHUB_WORKSPACE/outputs.json"
           fi
-        
+
       - name: Set Controller and Worker IPs as Environment Variables
-        if: ${{ success() && (steps.terraform_output.outputs.controller_public_ip != '' && steps.terraform_output.outputs.worker_public_ip != '') }}
         run: |
-          echo "controller_ip=$(jq -r .controller_public_ip.value outputs.json)" >> $GITHUB_ENV
-          echo "worker_ip=$(jq -r .worker_public_ip.value outputs.json)" >> $GITHUB_ENV
-        shell: /usr/bin/bash -e {0}
+          controller_ip=$(jq -r '.controller_public_ip.value // empty' "$GITHUB_WORKSPACE/outputs.json")
+          worker_ip=$(jq -r '.worker_public_ip.value // empty' "$GITHUB_WORKSPACE/outputs.json")
+          if [[ -z "$controller_ip" || -z "$worker_ip" ]]; then
+            echo "Error: Controller or Worker IP not found."
+            exit 1
+          fi
+          echo "controller_ip=$controller_ip" >> $GITHUB_ENV
+          echo "worker_ip=$worker_ip" >> $GITHUB_ENV
+        shell: bash
+
       - name: Create Ansible Inventory
         run: |
           echo "[k0s]" > ansible/inventory
-          echo "${{ env.controller_ip }} ansible_ssh_user=ubuntu" >> ansible/inventory
-          echo "${{ env.worker_ip }} ansible_ssh_user=ubuntu" >> ansible/inventory
+          echo "$controller_ip ansible_ssh_user=ubuntu" >> ansible/inventory
+          echo "$worker_ip ansible_ssh_user=ubuntu" >> ansible/inventory
 
       - name: Display inventory file content
         working-directory: ansible
