changes to pipeline

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -13,12 +13,10 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Set up Python
+      - name: Set up Python and Install Ansible
         uses: actions/setup-python@v4
         with:
           python-version: '3.x'
-
-      - name: Install Ansible
         run: |
           python -m pip install --upgrade pip
           pip install ansible
@@ -28,7 +26,7 @@ jobs:
         with:
           terraform_version: 1.5.0
 
-      - name: Run Terraform and capture outputs
+      - name: Run Terraform and Capture Outputs
         working-directory: infra
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -36,16 +34,15 @@ jobs:
         run: |
           terraform init
           terraform apply -auto-approve
-          terraform output -json > "$GITHUB_WORKSPACE/outputs.json"
+          terraform output -json | jq 'with_entries(select(.value.sensitive | not))' > "$GITHUB_WORKSPACE/outputs.json"
 
-      - name: Verify JSON Output and Structure
+      - name: Verify JSON Output Structure
         run: |
-          if [ ! -f "$GITHUB_WORKSPACE/outputs.json" ]; then
-            echo "Error: outputs.json was not created"
-            exit 1
+          if jq empty "$GITHUB_WORKSPACE/outputs.json" 2>/dev/null; then
+            echo "JSON file is valid."
           else
-            echo "Displaying outputs.json content:"
-            cat "$GITHUB_WORKSPACE/outputs.json" 
+            echo "Invalid JSON format in outputs.json"
+            exit 1
           fi
 
       - name: Set Controller and Worker IPs as Environment Variables
@@ -58,8 +55,6 @@ jobs:
           fi
           echo "controller_ip=$controller_ip" >> $GITHUB_ENV
           echo "worker_ip=$worker_ip" >> $GITHUB_ENV
-        shell: bash
-
 
       - name: Create Ansible Inventory
         run: |
@@ -67,10 +62,6 @@ jobs:
           echo "$controller_ip ansible_ssh_user=ubuntu" >> ansible/inventory
           echo "$worker_ip ansible_ssh_user=ubuntu" >> ansible/inventory
           cat ansible/inventory
-
-      - name: Display inventory file content
-        working-directory: ansible
-        run: cat inventory
 
       - name: Run Ansible Playbook
         env:
